repos:
- repo: https://github.com/biomejs/pre-commit
  rev: "v2.4.6"
  hooks:
  - id: biome-check
    additional_dependencies: ["@biomejs/biome@2.4.6"]
    files: \.(jsx?|tsx?|c(ss|js|ts)|m(js|ts)|jsonc?|html)$
